module.exports = {
  URL_API: process.env.URL_API,
  ROUTE_VERSION: process.env.ROUTE_VERSION,
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
  URL_APGATEWAY: process.env.URL_APGATEWAY,
  FEATURE_FLAGS: process.env.FEATURE_FLAGS,
  ID_TOKEN_KEY: process.env.ID_TOKEN_KEY,
  SESSION_TOKEN_KEY: process.env.SESSION_TOKEN_KEY,
  URL_API_MANAGEMENT: process.env.URL_API_MANAGEMENT
}
